import { WritableSignal } from "@angular/core";

// Defines the different views or pages in the application.
export type View = 'home' | 'ecommerce-editor' | 'automotive-editor' | 'generation-result' | 'pdf-result';

// Defines the types of listings the application supports.
export type ListingType = 'ecommerce' | 'automotive';

// Base interface for all listings, containing common properties.
export interface Listing {
  id: string;
  listingType: ListingType;
  title?: string;
  [key: string]: any; // Allows for additional, dynamic properties.
}

// Interface for e-commerce product listings.
export interface EcommerceListing extends Listing {
  listingType: 'ecommerce';
  productName?: string;
  condition?: string;
  brand?: string;
  model?: string;
  description?: string;
  price?: number;
  quantity?: number;
  category?: string;
  notes?: string;
}

// Interface for automotive listings.
export interface AutomotiveListing extends Listing {
  listingType: 'automotive';
  VIN?: string;
  Year?: number;
  Make?: string;
  Model?: string;
  Trim?: string;
  Mileage?: number;
  ColorExterior?: string;
  ColorInterior?: string;
  Transmission?: string;
  Engine?: string;
  Drivetrain?: string;
  FuelType?: string;
  BodyType?: string;
  ConditionNotes?: string;
  SpecialFeatures?: string;
  AuctionID?: string;
  AuctionDate?: string;
}

// Interface for the data generated by the AI for e-commerce listings.
export interface GeneratedData {
  title: string;
  html: string;
  category?: string;
  condition?: string;
  price?: number;
  brand?: string;
  model?: string;
  quantity?: number;
}

// Interface for vehicle data extracted from photos.
export interface VehicleData {
    VIN?: string;
    Year?: number;
    Make?: string;
    Model?: string;
    Trim?: string;
    ColorExterior?: string;
    ColorInterior?: string;
    Transmission?: string;
    Engine?: string;
    FuelType?: string;
    BodyType?: string;
    Drivetrain?: string;
    Mileage?: number;
    AuctionID?: string;
}

// Interface for cosmetic damage reports.
export interface DamageReport {
    type: 'scratch' | 'dent' | 'crack' | 'wheel_rash' | 'rust' | 'paint_fade' | 'chip';
    location: string;
    severity: number; // 0-5
    photoIndex: number;
    confidence: number; // 0-1
}

// Interface for the complete analysis of vehicle photos.
export interface VehiclePhotoAnalysis {
  vehicle_data: Partial<VehicleData>;
  photo_categorization: { [key: string]: number | null };
  damages?: DamageReport[];
}
